name: Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  run:
    name: Build (${{ matrix.python-version }} | ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        os: [ubuntu-latest]
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Micromamba ${{ matrix.python-version }}
        uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: xenso
          init-shell: bash
          create-args: >-
            python=${{ matrix.python-version }} pip
            --file requirements.txt
            --file requirements-dev.txt
            --channel conda-forge

      - name: Install the package
        run: pip install -e . --no-deps

      - name: Version info
        run: conda list

      - name: Run tests
        run: pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: false
